include:
  - project: infrastructure/gitlab-ci-templates
    file: /templates/deploy.yaml


stages:
  - publish-image
  - deploy


publish-image-to-pegah-registry:
  extends: .publish-pegah-registry-template
  stage: publish-image
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - if: $CI_COMMIT_BRANCH == "stage"
      when: on_success
    - when: never
  variables:
    IMAGE_TAG: $CI_PIPELINE_ID-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA


deploy-staging:
  extends: .deploy-template
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "stage"
      when: on_success
    - when: never
  variables:
    CLUSTER: Staging
    NAMESPACE: stg-genx
    APP: aision-midjourney-api
    IMAGE_TAG: $CI_PIPELINE_ID-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA


deploy-production:
  extends: .deploy-template
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - when: never
  variables:
    CLUSTER: Production
    NAMESPACE: genx
    APP: aision-midjourney-api
    IMAGE_TAG: $CI_PIPELINE_ID-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
